#!/bin/bash
set -Ceu

read -p "How many nodes do you wanna use? [integer]: " n_nodes
md_no=$(cat md_stage.inp | awk '{print $1}')

echo 'Making directories ...'
for inode in $(seq 1 $n_nodes)
do
    echo "mkdir -p md${md_no}/n${inode}"
    mkdir -p md${md_no}/n${inode}
done
